name: Test
on: [push]
jobs:
  test:
    name: functional tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-env name=COMPOSER_CACHE_DIR::$(composer config cache-files-dir)"
      - name: Cache Composer downloads
        uses: actions/cache@v1
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
      - name: Install Composer dependencies
        uses: php-actions/composer@master
        with:
          command: install
      - name: Run tests
        run: vendor/bin/codecept run functional

